require('./modules/app.js');
require('./modules/directives.js');
require('./services/d3.js');
require('./services/notify.js');
require('./services/pathParser.js');
require('./services/restConverter.js');
require('./services/shipApi.js');
require('./services/shipApiUiWrapper.js');
require('./components/app/add/appAddCtrl.js');
require('./components/app/detail/appDetailCtrl.js');
require('./components/app/general/appGeneralCtrl.js');
require('./components/app/list/appListCtrl.js');
require('./components/build/buildCtrl.js');
require('./components/builds/buildsCtrl.js');
require('./components/lanesGraph/lanesGraph.js');
require('./components/lanesGraph/src/lanesGraphCtrl.js');
require('./components/laneTemplates/laneTemplatesCtrl.js');
require('./components/navigation/navCtrl.js');
Action_Template = require('./models/Action_Template.js');
App = require('./models/App.js');
Build = require('./models/Build.js');
Lane_Template = require('./models/Lane_Template.js');
